spring:
  application:
    name: screanMatch
  jackson:
    date-format: io.swagger.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false  main:
    web-application-type: none
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/screen_match
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true